[package]
name = "nrf52833_playground"
version = "0.2.1"
edition = "2021"

[dependencies]
sh1106 = "0.5.0"
cortex-m = "0.7.3"
panic-halt = "1.0.0"
cortex-m-rt = "0.7.0"
embedded-hal = "1.0.0"
nrf52833-hal = "0.18.0"
embedded-graphics = "0.8.1"

[lints.clippy]
pedantic = "warn"
